network/urls.py
from django.urls import path

from . import views

app_name = "network"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # api paths
    path('post', views.post, name="post"),
    path('like', views.like, name="like"),
    path('profile', views.profile, name="profile"),
    path('follow', views.follow, name="follow"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Represent a user with:
        username, first_name, last_name, email and password"""
    def __str__(self):
        return f"{self.username}"


# posts
class Post(models.Model):
    """Represents a post by a user"""
    # user who posted the post
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    # text content of the post
    content = models.CharField(max_length = 280)

    # all users who liked this post
    liked_by = models.ManyToManyField(User, blank=True, related_name="likes")

    # datetime when post last updated or post for the first time
    datetime = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"Post {self.id} by {self.user}"

    def serialize(self):
        return {
            'id': self.id,
            'user': self.user.username,
            'firstname': self.user.first_name.capitalize(),
            'lastname': self.user.last_name.capitalize(),
            'content': self.content,
            'datetime': self.datetime.strftime("%b %d %Y, %I:%M %p")
        }


# followers
class Follow(models.Model):
    """Represents a follow-follower relationship between two users"""
    # user who followed other user
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")

    # the user who was followed by the above user
    followed_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers")

    def __str__(self):
        return f"{self.user} follows {self.followed_user}"

    class Meta:
        constraints = [
            # 'a' can't follow 'b' two times at the same. if (a,b) exist then don't create another pair
            models.UniqueConstraint(fields=['user', 'followed_user'], name='unique_follow_pair'),
        ]

    def save(self, *args, **kwargs):
        # Don't create a follow when user and followed_user are same
        if self.user.username == self.followed_user.username:
            return
        super().save(*args, **kwargs)

network/forms.py
from django import forms

network/views.py
import json
import datetime

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator

from .models import *
from .utils import validEmail


def index(request):
    return render(request, "network/index.html")


def post(request):
    """Saves a post with post method or get a post with get method"""
    if request.method == "POST":
        """Saves a post by user to database"""

        # check if user is signed in or not
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'please login to post'}, status=401)

        # get data from body of the request
        post_data = json.loads(request.body)
        # clean the content
        post_data['content'] = str(post_data['content']).strip()

        # check validity of form
        if post_data['content'] == "" or len(post_data['content']) > 280:
            return JsonResponse({'error': 'Please enter some text(maximum length:280)'}, status=400)

        # create post
        post = Post.objects.create(user=request.user, content=post_data['content'])

        # return the post created
        post = post.serialize()
        post['num_of_likes'] = Post.objects.get(pk = post['id']).liked_by.count()
        post['liked'] = request.user in Post.objects.get(pk = post['id']).liked_by.all()

        return JsonResponse(post, status=201)
    elif request.method == "GET":
        view = request.GET['view']
        username = request.GET.get('user', request.user).strip()

        # if user value is empty then it means the current user's post is needed
        if not username:
            username = request.user.username
        # get the user from username
        user = None
        if view != "all_posts": # no need for user in all_posts
            user = User.objects.get(username=username)

        if view == "all_posts":
            posts = Post.objects.all()
        elif view == "profile":
            posts = Post.objects.filter(user=user)
        elif view == "following":
            following_users = request.user.following.values_list('followed_user')
            posts = Post.objects.filter(user__in = following_users)
        else:
            return JsonResponse({'error':'Invalid view option'}, status=400)

        # return posts in reverse chronological order
        posts = posts.order_by("-datetime").all()

        # apply pagination
        page_number = int(request.GET['page'])
        posts_paginator = Paginator(posts, 10) # Show 10 posts per page.
        total_pages = posts_paginator.num_pages

        # convert posts to dictionary
        posts = [post.serialize() for post in posts_paginator.page(page_number)]

        # add number of likes to each post dictioanary in posts array
        # and add whether user has liked the post or nor
        for post in posts:
            post['num_of_likes'] = Post.objects.get(pk = post['id']).liked_by.count()
            post['liked'] = request.user in Post.objects.get(pk = post['id']).liked_by.all()
            post['active_user'] = request.user.username

        return JsonResponse({
            'posts': posts, 
            'total_pages': total_pages,
        }, status=200)
    elif request.method == "PUT":
        """Edits the post"""
        # check if user is signed in or not
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'please login to post'}, status=401)

        # get data from body of the request
        new_post_data = json.loads(request.body)
        # clean the content
        new_post_data['new_content'] = str(new_post_data['new_content']).strip()

        # check validity of new content
        if new_post_data['new_content'] == "" or len(new_post_data['new_content']) > 280:
            return JsonResponse({'error': 'Please enter some text(maximum length:280)'}, status=400)

        # get post
        post = Post.objects.get(pk=new_post_data['id'])

        # you cannot edit others post
        if (post.user != request.user):
            return JsonResponse({'error': "You cannot edit other's post"}, status=400)

        # update the post
        post.content = new_post_data['new_content']
        post.datetime = datetime.datetime.now()
        post.save()

        # return the post created
        post = post.serialize()
        post['num_of_likes'] = Post.objects.get(pk = post['id']).liked_by.count()
        post['liked'] = request.user in Post.objects.get(pk = post['id']).liked_by.all()

        return JsonResponse(post, status=201)


def like(request):
    """toggles like of a post"""
    if request.method == "PUT":
        # check if user is signed in or not
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('network:index'))

        data = json.loads(request.body)
        
        try:
            post = Post.objects.get(pk=data['post_id'])
        except:
            return JsonResponse({'error': 'post not found'}, status=404)
        
        # add or remove like to post by current user
        if not data['like'] and request.user not in post.liked_by.all():
            post.liked_by.add(request.user)
        else:
            post.liked_by.remove(request.user)

        post.save()
        return JsonResponse({'responce': 'success'}, status = 201)
    else:
        return HttpResponseRedirect(reverse('network:index'))

def profile(request):
    username = request.GET['username'].strip()
    if not username:
        username = request.user.username
    
    # Get the user from username
    user = User.objects.get(username=username)

    is_followed = False
    if request.user.is_authenticated:
        for user_ in request.user.following.all().values('followed_user'):
            if user.id == user_['followed_user']:
                is_followed = True

    userInfo = {
        'id': user.id,
        'user': user.username,
        'active_user': request.user.username,
        'firstname': user.first_name.capitalize(),
        'lastname': user.last_name.capitalize(),
        'following': user.following.count(),
        'followers': user.followers.count(),
        'followed': is_followed,
    }

    return JsonResponse(userInfo, status=200)


def follow(request):
    if request.method == "PUT":
        data = json.loads(request.body)

        followed_user_id = data['followed_user_id']
        follow_state = data['follow_state']

        # Get user from user id
        followed_user = User.objects.get(pk=followed_user_id)

        # confirm followed user is different from active user
        if followed_user == request.user:
            return JsonResponse({'error': 'You cannot follow yourself'}, status=400)

        # toggle follow
        try:
            # if not exists then create new follow
            follow = Follow.objects.create(user=request.user, followed_user=followed_user)
        except IntegrityError:
            # if exists then delete that follow
            follow = Follow.objects.get(user=request.user, followed_user=followed_user)
            follow.delete()

        return JsonResponse({'success': 'follow created successfully'}, status=201)
    if request.method == "GET":
        category = str(request.GET['category'])
        username = str(request.GET['user'])

        # Get user
        user = User.objects.get(username=username)

        if category == "following":
            # get followed users of active user
            followingUsers = user.following.all()
            follows = [user.followed_user.username for user in followingUsers]
        elif category == "followers":
            # get follower of active_users
            followerUsers = user.followers.all()
            follows = [user.user.username for user in followerUsers]
        else:
            return JsonResponse({'error': 'Invalid Category'}, status=400)
        
        return JsonResponse(follows, safe=False, status=200)

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authetication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            }, status=401)
    else:
        # if user is already logged in then go to index
        if request.user.is_authenticated:\
            return HttpResponseRedirect(reverse('network:index'))
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        for value in request.POST.values():
            if not value:
                return render(request, "network/register.html", {
                        "message": "Please provide all fields.",
                    }, status=400)

        if not validEmail(request.POST['email']):
            return render(request, "network/register.html", {
                "message": "Email is not valid",
            }, status=400)

        username = request.POST["username"]
        email = request.POST["email"]
        first_name = request.POST["firstname"]
        last_name = request.POST['lastname']

        # Ensure password matches the confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match",

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block main %}
<div id="user-view">
</div>


{% if user.is_authenticated %}
<div id="new-post" class="mb-4">
    <form method="POST" id="new-post-form" novalidate>
        {% csrf_token %}
        <textarea name="content" id="id_content" rows="4" placeholder="What's in your mind" maxlength="280" required></textarea>
        <div class="invalid-feedback text-center alert alert-danger m-0 rounded-0">Please enter some text(maximum length:280)</div>
        <button type="submit" class="post-btn btn btn-block btn-dark d-block ml-auto">Post</button>
    </form>
</div>
{% else %}
<div id="new-post">
    <form method="POST" id="new-post-form" novalidate>
        {% csrf_token %}
        <textarea name="content" id="id_content" rows="4" placeholder="Please login to post" maxlength="280" required disabled></textarea>
        <div class="invalid-feedback text-center alert alert-danger m-0 rounded-0">Please enter some text(maximum length:280)</div>
        <button type="submit" class="post-btn btn btn-block btn-dark d-block ml-auto" disabled>Post</button>
    </form>
</div>
{% endif %}

<div id="posts-view">
</div>


<nav id="page-nav-button">
        <ul class="pagination justify-content-between">
          <li class="page-item disabled"><button class="page-link" id="previous-btn" disabled>Previous</button></li>
          <li class="page-item"><button class="page-link px-4" id="next-btn">Next</button></li>
        </ul>
</nav>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Social Network{% endblock %}</title>

        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <link href="{% static 'network/styles/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-sm navbar-dark mb-2" id="main-nav">
            <a class="navbar-brand" href="{% url 'network:index' %}">Network</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse justify-content-end" id="main-navbar">
              <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <button class="nav-link btn" id="profile"><strong>{{ user.username }}</strong></button>
                    </li>
                {% endif %}
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <button class="nav-link btn" id="all-posts">All Posts</button>
                    {% else %}
                        <a href="{% url 'network:index' %}" class="nav-link">All Posts</a>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <button class="nav-link btn" id="following">Following</button>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="container">
            <div id="main">
                {% block main %}
                {% endblock %}
            </div>
        </div>

        {% if user.is_authenticated%}
            <script src="{% static 'network/scripts/main.js' %}" type="module"></script>
        {% else %}
            <script src="{% static 'network/scripts/notlogin.js' %}" type="module"></script>
        {% endif %}

        <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block title %}
    Login | Social Network
{% endblock %}

{% block main %}
    <h1 class="text-center display-4">Login</h1>

    <div id="login-section" class="bg-dark p-4 rounded-lg text-white">
        {% if message %}
            <div class="alert alert-warning text-center">{{ message }}</div>
        {% endif %}

        <form action="{% url 'network:login' %}" id="login-form" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_username" class="input-group-text">Username</label>
                </div>
                <input autofocus class="form-control" type="text" name="username" id="id_username" placeholder="Username" required>
                <div class="invalid-feedback">Please Enter Username.</div>
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_password" class="input-group-text">Password</label>
                </div>
                <input class="form-control" type="password" name="password" id="id_password" placeholder="Password" required>
                <div class="invalid-feedback">Please Enter Password.</div>
            </div>
            <input class="btn btn-primary btn-block" type="submit" value="Login">
        </form>

        <div class="text-center mt-3 mb-0">
            Don't have an account? <a class="text-success" href="{% url 'network:register' %}">Register here.</a> 
        </div>
    </div>

    <script>
        'use strict'
        const loginForm = document.querySelector('#login-form');
        loginForm.addEventListener('submit', (e) => {
            if (loginForm.checkValidity() === false) {
                e.preventDefault();
                loginForm.classList.add('was-validated');
            }
        });
    </script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block title %}
    Register | Social Network
{% endblock %}

{% block main %}
    <h1 class="text-center display-4">Register</h1>

    <div id="register-section" class="bg-dark p-4 rounded-lg text-white">
        {% if message %}
            <div class="alert alert-warning text-center">{{ message }}</div>
        {% endif %}

        <form action="{% url 'network:register' %}" method="post" id="register-form" novalidate>
            {% csrf_token %}
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_firstname" class="input-group-text">First Name</label>
                </div>
                <input class="form-control" autofocus type="text" name="firstname" id="id_firstname" placeholder="First Name" required>
                <div class="invalid-feedback">Please Enter First Name.</div>
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_lastname" class="input-group-text">Last Name</label>
                </div>
                <input class="form-control" autofocus type="text" name="lastname" id="id_lastname" placeholder="Last Name" required>
                <div class="invalid-feedback">Please Enter Last Name.</div>
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_username" class="input-group-text">Username</label>
                </div>
                <input class="form-control" autofocus type="text" name="username" id="id_username" placeholder="Username" required>
                <div class="invalid-feedback">Please Enter Username.</div>
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_email" class="input-group-text">Email</label>
                </div>
                <input class="form-control" type="email" name="email" id="id_email" placeholder="Email Address" required>
                <div class="invalid-feedback">Please Enter Email.</div>
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="password" class="input-group-text">Password</label>
                </div>
                <input class="form-control" type="password" name="password" placeholder="Password" required>
                <div class="invalid-feedback">Please Enter Password.</div>
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <label for="id_confirmation" class="input-group-text">Confirm Password</label>
                </div>
                <input class="form-control" type="password" name="confirmation" id="id_confirmation" placeholder="Password" required> 
                <div class="invalid-feedback">Please Confirm Your Password.</div>
            </div>
            <input class="btn btn-primary btn-block" type="submit" value="Register">
        </form>

        <div class="text-center mt-3 mb-0">
            Already have an account? <a class="text-success" href="{% url 'network:login' %}">Log In here.</a>
        </div>
    </div>

    <script>
        'use strict'
        const registerForm = document.querySelector('#register-form');
        registerForm.addEventListener('submit', (e) => {
            if (registerForm.checkValidity() === false) {
                e.preventDefault();
                registerForm.classList.add('was-validated');
            }
        });
    </script>
{% endblock %}